name: GSheets Test

on:
  push:
env:
  id: '1om6T_FqSoBbWDn30R2i4tP-KrS_N05tlQ-YFF_-f74A'
  name: 'Archive'
  range: 'A1:R101'

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Pull GSheet data
        id: 'sheet_to_csv'
        uses: dolthub/gsheets-to-csv@1
        with:
          creds: ${{ secrets.GSHEET_PRIVATE_KEY }}
          sheets: |
            [
              { "id": "${{ env.id }}", "range": "${{ env.range }}", "title": "${{ env.name }}" },
              { "id": "${{ env.id }}" }
            ]
      - name: Print CSV
        id: "print_csv"
        env:
          FILES: ${{ steps.sheet_to_csv.outputs.results }}
        run: |
          file_list=($FILES)
          for file in "${file_list[@]}"; do
              echo "$(wc -l $file)"
          done
